name: Google C++ CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu klonla
        uses: actions/checkout@v4

      - name: Gerekli araçları yükle
        run: |
          sudo apt update
          sudo apt install -y cmake g++ clang-tidy clang-format-14 cppcheck

      - name: CMake yapılandırmasını çalıştır
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Projeyi derle
        run: |
          cd build
          make -j$(nproc)

      - name: Google C++ Stil Kontrolü (Clang-Format)
        run: find . -name "*.cpp" -o -name "*.h" | xargs clang-format-14 --style=Google --dry-run --Werror

      - name: Kod analizi (Cppcheck)
        run: cppcheck --enable=all --inconclusive --quiet --error-exitcode=1 .

      - name: Google Test'leri çalıştır
        run: |
          cd build
          ctest --output-on-failure

      - name: Google C++ Kod İnceleme (Clang-Tidy)
        run: clang-tidy src/*.cpp -- -Iinclude -checks="google-*"
